-- Initial products data for Quickzo
-- Uses INSERT IGNORE to prevent duplicate records and preserve modified data on re-runs
INSERT IGNORE INTO product (id, name, quantity) VALUES (1, 'Moisturizer', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (2, 'Sunscreen', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (3, 'Serum', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (4, 'Sheetmask', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (5, 'Aloevera Gel', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (6, 'Vaseline', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (7, 'Ice Roller', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (8, 'Micellar Water', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (9, 'Milk', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (10, 'Bread', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (11, 'Eggs', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (12, 'Refined Oil', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (13, 'Rajma Beans', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (14, 'Masoor', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (15, 'Soya Beans', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (16, 'Idli Batter', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (17, 'Banana', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (18, 'Chikoo', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (19, 'Grapes', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (20, 'Dragon Fruit', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (21, 'Onion', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (22, 'Lady Finger', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (23, 'Potato', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (24, 'Bottle Gourd', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (25, 'Color Pens', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (26, 'Craft Papers', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (27, 'Notebooks', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (28, 'Geometry', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (29, 'Sketch Book', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (30, 'Color Kit', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (31, 'Color Tapes', 50);
INSERT IGNORE INTO product (id, name, quantity) VALUES (32, 'Whitener', 50);
