INSERT INTO PRODUCT (name, quantity) VALUES ('Moisturizer', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Sunscreen', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Serum', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Sheetmask', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Aloevera Gel', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Vaseline', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Ice Roller', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Micellar Water', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Milk', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Bread', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Eggs', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Refined Oil', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Rajma Beans', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Masoor', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Soya Beans', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Idli Batter', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Banana', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Chikoo', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Grapes', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Dragon Fruit', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Onion', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Lady Finger', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Potato', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Bottle Gourd', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Color Pens', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Craft Papers', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Notebooks', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Geometry', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Sketch Book', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Color Kit', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Color Tapes', 50);
INSERT INTO PRODUCT (name, quantity) VALUES ('Whitener', 50);